# Generated by Django 4.1.2 on 2023-05-15 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('servico', models.CharField(max_length=100, verbose_name='servico')),
                ('data', models.DateField(verbose_name='data')),
                ('horario', models.TimeField(verbose_name='horario')),
            ],
        ),
        migrations.CreateModel(
            name='Barbeiro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, verbose_name='nome_barbeiro')),
            ],
        ),
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('horarios', models.TimeField(verbose_name='horario')),
            ],
        ),
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('servicos', models.CharField(max_length=100, verbose_name='servicos')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
        ),
    ]
