# Generated by Django 4.2.1 on 2023-05-18 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_agendamento_horario_alter_horarios_horarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
